Feat: upload endpoint
metakgp/iqps-go pull request #39
Opened 2024-04-19 21:19 UTC by shikharish

2024-04-20 03:53 UTC, rajivharlalka requested changes

2024-04-20 03:53 UTC, rajivharlalka commented on backend/main.go
> +	}
How are you using this err to show the user that the fille upload has failed?

2024-04-20 03:53 UTC, rajivharlalka commented on backend/main.go
> +		filename := strings.ReplaceAll(fileHeader.Filename, ":", "_")
Let's change the convention to having just `<course_no>_year_mids/end_spring/autumn.pdf`

2024-04-20 03:53 UTC, rajivharlalka commented on backend/main.go
> +	fileByte, err := os.ReadFile("courses.json")
seems like an unnecessary thing to be done for every file. can put this data in another table in the database itself.

2024-04-20 03:53 UTC, rajivharlalka commented on backend/main.go
> +	files := r.MultipartForm.File["file"]
```suggestion
	files := r.MultipartForm.File["files"]
```

2024-04-20 03:53 UTC, rajivharlalka commented on backend/main.go
> +		dest, err := os.Create(filePath)
what if the same filename exists previously?

2024-04-20 03:53 UTC, rajivharlalka commented on backend/main.go
> +		fmt.Println("Size", fileHeader.Size)
remove

2024-04-20 03:57 UTC, rajivharlalka commented on backend/main.go
> +	qpData := strings.Split(filename, ":")
also remove the last `.pdf` from the last part of filename

2024-04-20 07:09 UTC, shikharish commented on backend/main.go
> +		filename := strings.ReplaceAll(fileHeader.Filename, ":", "_")
Did not get that comment.

2024-04-20 07:10 UTC, shikharish commented on backend/main.go
> +	fileByte, err := os.ReadFile("courses.json")
Alight. Will change it assuming the data is already present in the db.

2024-04-20 07:15 UTC, shikharish commented on backend/main.go
> +	qpData := strings.Split(filename, ":")
Why so? We are not storing the filename in the db anyways.

2024-04-20 08:15 UTC, rajivharlalka commented on backend/main.go
> +	fileByte, err := os.ReadFile("courses.json")
Yes

2024-04-20 08:16 UTC, rajivharlalka commented on backend/main.go
> +		filename := strings.ReplaceAll(fileHeader.Filename, ":", "_")
Your filename wouldn't have : as seperator instead _

So technically you don't need that line since you would not need to change the file name

2024-04-20 08:17 UTC, rajivharlalka commented on backend/main.go
> +	qpData := strings.Split(filename, ":")
Filename would have .pdf in the name

2024-04-20 08:18 UTC, rajivharlalka commented
Fileheader.filename would essentially be 
`courseNo_year_midsem/endsem_spring/autumn.pdf`

2024-04-20 08:19 UTC, shikharish commented on backend/main.go
> +	qpData := strings.Split(filename, ":")
Why do we need to remove the .pdf? That part is never used anyways

2024-04-20 08:39 UTC, shikharish commented on backend/main.go
> +	}
made some improvements

2024-04-20 08:41 UTC, rajivharlalka commented on backend/main.go
> +		}
if  file 2/5 could not be uploaded to the db and the user is provided an error that the file could not be uploaded:
- what happens about the previous added files?
- the file created on the system still persists which can accumulate to a lot in a long run.

2024-04-20 08:50 UTC, rajivharlalka commented on backend/main.go
> +				if _, err := os.Stat(fmt.Sprintf("%s-%d", filePath, i)); err == nil {
It looks like %s-%d you mean that the copy of the file would be named with a - and a number. But is that a general conventation everywhere? In my system a duplicate file is create with `a (Copy)` if a file with name `a` exists

2024-04-21 13:10 UTC, harshkhandeparkar commented on backend/main.go
> +		if _, err = os.Stat(filePath); err == nil {
Is it possible to store filename in db and run a query instead of running fs ops for duplicate filename handling

2024-04-21 13:10 UTC, harshkhandeparkar commented on backend/main.go
> +	rows := db.QueryRow("SELECT course_name FROM courses WHERE course_code=$1", code)
isn't it inefficient to query the db for this? Would be better to just hardcode the values in a map.

2024-04-21 13:36 UTC, rajivharlalka commented on backend/main.go
> +	rows := db.QueryRow("SELECT course_name FROM courses WHERE course_code=$1", code)
Didn't think much efficiency here but when a new course has to be added, it would be a bit of pain to be added in the map than a database.

2024-04-21 13:36 UTC, rajivharlalka commented on backend/main.go
> +		if _, err = os.Stat(filePath); err == nil {
Didnt get you

2024-04-21 13:36 UTC, rajivharlalka commented on backend/main.go
> +	if len(files) > 5 {
Chirag wanted this, to limit spam

2024-04-21 14:10 UTC, harshkhandeparkar commented on backend/main.go
> +	rows := db.QueryRow("SELECT course_name FROM courses WHERE course_code=$1", code)
If we are going to use a separate map in the frontend, I don't think adding it to the db makes any sense. Also, adding a new course to the code won't be that hard, just one commit and it will auto deploy.

2024-04-21 14:10 UTC, harshkhandeparkar commented on backend/main.go
> +		if _, err = os.Stat(filePath); err == nil {
For checking duplicate files, is it possible to do it from the db rather than by reading files from storage?

2024-04-21 14:11 UTC, harshkhandeparkar commented on backend/main.go
> +	if len(files) > 5 {
I think a 6-8 file limit would be better so people with > 5 courses can send all of their papers at once.

2024-04-25 10:56 UTC, shikharish commented on backend/main.go
> +	err := r.ParseMultipartForm(MaxBodySize)
`r.ParseMultipartForm` will return an error.

2024-04-25 10:58 UTC, shikharish commented on backend/main.go
> +		if _, err = os.Stat(filePath); err == nil {
>For checking duplicate files, is it possible to do it from the db rather than by reading files from storage?

Agree, this is better.

2024-04-25 11:00 UTC, shikharish commented on backend/main.go
> +	rows := db.QueryRow("SELECT course_name FROM courses WHERE course_code=$1", code)
Can just use a courses.json then. It will be parsed to a map when backend starts.

2024-04-25 14:18 UTC, rajivharlalka commented
yes, please do that


On Thu, Apr 25, 2024 at 4:30 PM Shikhar Soni ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In backend/main.go
> <https://github.com/metakgp/iqps-go/pull/39#discussion_r1579282323>:
>
> > +
> +	year, _ := strconv.Atoi(qpData[1])
> +	exam := qpData[2]
> +	fromLibrary := false
> +	fileLink := fmt.Sprintf("%s/%s", staticFilesUrl, filename)
> +	query := "INSERT INTO qp (course_code, course_name, year, exam, filelink, from_library) VALUES ($1, $2, $3, $4, $5, $6);"
> +
> +	_, err = db.Exec(query, courseCode, courseName, year, exam, fileLink, fromLibrary)
> +	if err != nil {
> +		return fmt.Errorf("failed to add qp to database: %v", err)
> +	}
> +	return nil
> +}
> +
> +func mapCodeToName(code string) (string, error) {
> +	rows := db.QueryRow("SELECT course_name FROM courses WHERE course_code=$1", code)
>
> Can just use a courses.json then. It will be parsed to a map when backend
> starts.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/metakgp/iqps-go/pull/39#discussion_r1579282323>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQMMFH7L5CYNMRAGXQCBVR3Y7DO4XAVCNFSM6AAAAABGP276CKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMRSGE4DMOBXHE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-04-26 09:24 UTC, rajivharlalka commented
@shikharish things pending here?

2024-04-26 09:35 UTC, shikharish commented
@rajivharlalka Yes.

2024-04-26 10:14 UTC, rajivharlalka commented
what?

2024-05-09 17:53 UTC, harshkhandeparkar approved these changes

2024-05-09 17:54 UTC, merged

2024-05-09 17:54 UTC, harshkhandeparkar commented
jai mata di