Added dev docker compose for dev database
metakgp/iqps-go pull request #66
Opened 2024-06-01 08:27 UTC by Bikram-ghuku

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Run the docker image with docker compose command and test with go run .
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-01 13:39 UTC, harshkhandeparkar requested changes

2024-06-01 13:39 UTC, harshkhandeparkar commented on README.md
> +3. Start the backend by running `go run .` in the `backend/` directory.
Can we add either:
1. A line here that tells the user to set the database host etc to `locahost`, or
2. A `DEV` environment variable which does the same if true.

2024-06-02 04:41 UTC, Bikram-ghuku commented on README.md
> +3. Start the backend by running `go run .` in the `backend/` directory.
Made a new commit for the updated README

2024-06-02 09:56 UTC, harshkhandeparkar commented on README.md
> +    - Fill the env variable and set `DB_HOST=localhost` for running locally for development
Port also has to be set :)

2024-06-02 09:56 UTC, harshkhandeparkar commented on README.md
> +    - Fill the env variable and set `DB_HOST=localhost` for running locally for development
And all the other variables as well lol

2024-06-02 09:57 UTC, harshkhandeparkar commented on README.md
> +    - Fill the env variable and set `DB_HOST=localhost` for running locally for development
There is already a separate section for env vars. Perhaps you can update it?

2024-06-02 19:40 UTC, harshkhandeparkar approved these changes

2024-06-03 11:16 UTC, shikharish commented on backend/docker-compose.dev.yaml
> +      - POSTGRES_DB=${DB_NAME}
You need to add `PGPORT` and `PGHOST` as environment variables here, as such:
```
      - PGPORT=${DB_PORT}
      - PGHOST=${DB_HOST}
```

2024-06-03 11:16 UTC, shikharish commented on README.md
> +    - Start the DB by running `sudo docker compose -f docker-compose.dev.yaml up -d`
no need for sudo here.

2024-06-03 11:16 UTC, shikharish commented on README.md
> +    - Fill the env variable and set `DB_HOST=localhost` and `DB_PORT=5432` for running locally for development
DB_HOST will be localhost but let the developer set the port as per their choice.

2024-06-03 16:29 UTC, harshkhandeparkar commented
@shikharish merge if you approve.

2024-06-03 16:33 UTC, shikharish approved these changes

2024-06-03 16:35 UTC, merged

2024-06-03 16:35 UTC, shikharish commented
Thanks for your contribution!