Create Admin Page frontend
metakgp/iqps-go pull request #67
Opened 2024-06-04 11:19 UTC by Majestic9169

## Plan

- [x] create table to list question papers
- [ ] make question paper details editable
- [ ] filter capability based on approval status
- [ ] show approved by/rejected by
- [ ] modal to view pdf

Fixes # (63)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

2024-06-05 16:03 UTC, harshkhandeparkar requested changes

2024-06-05 16:03 UTC, harshkhandeparkar commented on frontend/src/components/PDFLister.tsx
> +    // createShortcut(
?

2024-06-05 16:03 UTC, harshkhandeparkar commented on frontend/src/components/PDFLister.tsx
> +            <td><input type="string" value={questionPaperDetails.semester} onInput={(e) => setQuestionPaperDetails("semester", e.target.value)} readonly={!props.isEditMode}/></td>
You can make these select inputs since they only have a few options.

2024-06-05 16:03 UTC, harshkhandeparkar commented on frontend/src/components/PDFLister.tsx
> +            <td><input type="string" value={questionPaperDetails.course_code} onInput={(e) => setQuestionPaperDetails("course_code", e.target.value)} readonly={!props.isEditMode}/></td>
We have a list of course codes. You can make this a select input. Contact @rohan-b-84 for more information.

2024-06-05 16:03 UTC, harshkhandeparkar commented on frontend/src/components/PDFTable.tsx
> +    createShortcut(
I don't think we really need an "edit mode" for the entire page. We can have an edit button per paper that opens a modal that will have a form for editing.

2024-06-05 18:24 UTC, Majestic9169 commented on frontend/src/components/PDFTable.tsx
> +    createShortcut(
i'll implement this once i make the modal to view the pdf, until then if we're just using the new tab link functionality i feel like being able to see all the together will make the process faster

2024-06-05 18:34 UTC, harshkhandeparkar commented on frontend/src/components/PDFTable.tsx
> +    createShortcut(
> see all the question papers together will make the process faster

Hmm, true. In that case, instead of an edit mode, make an edit button that becomes enabled if something is changed. Clicking on it will update the data on the backend.

2024-06-12 15:37 UTC, harshkhandeparkar commented
I think we can skip the modal part. A link to the pdf is more than enough, it'll open in the browser's pdf viewer.

2024-06-12 16:25 UTC, Majestic9169 commented on frontend/src/components/PDFLister.tsx
> +            <td><input type="string" value={questionPaperDetails.semester} onInput={(e) => setQuestionPaperDetails("semester", e.target.value)} readonly={!props.isEditMode}/></td>
done, however I haven't been able validate that the course_code and course_name match

one idea I had was to have the course_name display the value from the courses.json file for the corresponding key, this should be doable using the format method in solid-select, however I wasn't able to figure it out. some help with that would be quite nice

2024-06-12 16:27 UTC, Majestic9169 commented
the modal part would probably be the last step, so yeah, we should have something functional before we get to that. I don't think we need to scrap it completely just yet though, we may be able to do something cool to make the approval process really fast with it

2024-06-12 16:30 UTC, Majestic9169 commented on frontend/src/components/PDFLister.tsx
> +    // createShortcut(
this was me playing arround with keyboard shortcuts to make approval faster, removed now

2024-06-12 16:31 UTC, Majestic9169 commented on frontend/src/components/PDFLister.tsx
> +            <td><input type="string" value={questionPaperDetails.course_code} onInput={(e) => setQuestionPaperDetails("course_code", e.target.value)} readonly={!props.isEditMode}/></td>
same as above requested change, so resolving

2024-06-12 16:34 UTC, Majestic9169 commented on frontend/src/components/PDFTable.tsx
> +    createShortcut(
i'm not very happy with my current approve/reject functionality, what other methods would you suggest, keeping in mind speed of approval? 
is a button fine?
do we need further confirmation before approval?
how can i make this process faster and error free? 
these are some questions I need to answer before I completely fix this, until then I'll make the table sortable

2024-06-19 18:33 UTC, Majestic9169 commented
I thought captions were useful if the table didn't load or for accessibility reasons

2024-06-19 19:05 UTC, harshkhandeparkar commented
> I thought captions were useful if the table didn't load or for accessibility reasons

Hmm, it looked weird in that place. Maybe we can add it back in the future when we (probably) add more features to the admin dashboard - stats etc.

2024-06-19 19:05 UTC, harshkhandeparkar commented
If the dashboard has multiple sections it would make more sense. Right now it is just a way to approve uploaded papers.

2024-08-25 17:22 UTC, harshkhandeparkar approved these changes
let's test this in prod

2024-08-25 17:23 UTC, merged