Added github OAuth endpoints
metakgp/iqps-go pull request #72
Opened 2024-06-13 15:12 UTC by Bikram-ghuku

# Description

Added github OAuth backend which takes in a code in JSON format and returns a JWT if authenticated else doesnt

Fixes #61  (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Created two user one part of the team and one not a part returns 401 for not authenticated  and 200 for authenticated

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-14 14:37 UTC, harshkhandeparkar requested changes

2024-06-14 14:37 UTC, harshkhandeparkar commented on backend/main.go
> +		"name": uname,
I think it is best to name the key `username` instead of `name.`

2024-06-14 14:37 UTC, harshkhandeparkar commented on backend/main.go
> +	err = json.NewEncoder(w).Encode(&tokenString)
Where is the response sent?

2024-06-14 14:37 UTC, harshkhandeparkar commented on backend/main.go
> +	http.HandleFunc("/ghreg", GhAuth)
I think `/oauth` makes more sense.

2024-06-14 14:40 UTC, Bikram-ghuku commented on backend/main.go
> +	err = json.NewEncoder(w).Encode(&tokenString)
`w` is the response writer so `json.NewEncoder(w).Encode(&tokenString)` sends the response

2024-06-14 14:42 UTC, harshkhandeparkar commented on backend/main.go
> +	err = json.NewEncoder(w).Encode(&tokenString)
So the content is just the string and not of type json?

2024-06-14 16:27 UTC, Bikram-ghuku commented on backend/main.go
> +	err = json.NewEncoder(w).Encode(&tokenString)
yes

2024-06-14 16:27 UTC, Bikram-ghuku commented on backend/main.go
> +	err = json.NewEncoder(w).Encode(&tokenString)
should I convert it to json?

2024-06-14 16:55 UTC, harshkhandeparkar commented on backend/main.go
> +	err = json.NewEncoder(w).Encode(&tokenString)
Yes, or do not set the `application/json` header.

2024-06-15 09:32 UTC, harshkhandeparkar requested changes

2024-06-15 09:32 UTC, harshkhandeparkar commented on backend/main.go
> +	http.Handle("/protected", JWTMiddleware(http.HandlerFunc(protectedRoute)))
I think we can remove this test route now.

2024-06-15 09:32 UTC, harshkhandeparkar commented on backend/main.go
> +		Token string `json:"tokenString"`
```suggestion
		Token string `json:"token"`
```

2024-06-15 12:04 UTC, Bikram-ghuku commented on backend/main.go
> +	http.Handle("/protected", JWTMiddleware(http.HandlerFunc(protectedRoute)))
I am commenting out this route and the handler

2024-06-15 12:25 UTC, harshkhandeparkar commented on backend/main.go
> +			fmt.Fprint(w, "Authorisation head is of inccorect type")
incorrect* lol

2024-06-15 15:00 UTC, harshkhandeparkar commented on backend/.env.template
> +TOKEN= # JWT encryption token
Better to name this `JWT_SECRET`

2024-06-15 17:08 UTC, harshkhandeparkar commented on backend/.env.template
> +JWT_TOKEN= # JWT encryption token
`JWT_SECRET` bola tha sir, it is not a token.

2024-06-15 18:28 UTC, rajivharlalka commented
@Bikram-ghuku it's recommended to resolve comments once you have made changes, helps in faster review.

2024-06-15 18:33 UTC, rajivharlalka commented on backend/main.go
> +		return
If we specify Go version 1.22 and above to be used, this can be written directly in the route line.
refer: https://go.dev/blog/routing-enhancements

2024-06-15 18:40 UTC, rajivharlalka requested changes

2024-06-15 18:40 UTC, rajivharlalka commented on backend/main.go
> +	bodyReg := BodyReg{}
rename variable names, unable to understand what BodyReg is

2024-06-15 18:40 UTC, rajivharlalka commented on backend/main.go
> +		http.Error(w, "Code cannot be empty", http.StatusBadRequest)
Which code?

2024-06-15 18:40 UTC, rajivharlalka commented on backend/main.go
> +func GhAuth(w http.ResponseWriter, r *http.Request) {
Also why is this a POST request?

2024-06-15 18:40 UTC, rajivharlalka commented on backend/main.go
> +func GhAuth(w http.ResponseWriter, r *http.Request) {
@harshkhandeparkar don't we do this in a GET request in kwoc signups 🤔

2024-06-15 18:40 UTC, rajivharlalka commented on backend/main.go
> +	jwt_secret = os.Getenv("JWT_SECRET")
What if the env aren't set?

2024-06-15 18:42 UTC, harshkhandeparkar commented on backend/main.go
> +func GhAuth(w http.ResponseWriter, r *http.Request) {
/shrug I don't remember exactly but either should work

2024-06-15 18:42 UTC, harshkhandeparkar commented on backend/main.go
> +func GhAuth(w http.ResponseWriter, r *http.Request) {
I remember having a conversation about whether using a single type of HTTP request for everything is better or using POST/PUT/DELETE and everything.

2024-06-15 18:45 UTC, Bikram-ghuku commented on backend/main.go
> +		return
https://github.com/metakgp/iqps-go/blob/main/backend/go.mod

This project uses go1.21.6

2024-06-15 18:53 UTC, harshkhandeparkar commented on backend/main.go
> +		return
We can make it 1.22. We run it Docker and we are the only ones running it anyway.

2024-06-15 18:54 UTC, Bikram-ghuku commented on backend/main.go
> +func GhAuth(w http.ResponseWriter, r *http.Request) {
Should I change to GET or keep it as POST ?

2024-06-15 18:58 UTC, harshkhandeparkar approved these changes
Consider it approved from my side. @rajivharlalka if you approve, please merge.

2024-06-17 09:15 UTC, harshkhandeparkar commented on backend/main.go
> +func GhAuth(w http.ResponseWriter, r *http.Request) {
let it be for now

2024-06-21 02:13 UTC, rajivharlalka commented on backend/main.go
> +type RequestBody struct {
RequestBody is quite a generic name for a struct with specific fields. If there an addition of an API later and needs creation of a struct, this would have to be renamed for clarity, so keep something more specific like `GithubOAuthRequestBody`

2024-06-21 02:13 UTC, rajivharlalka commented on backend/main.go
> +		return
Why was this resolved? Are we moving to Go 1.22 or not?

2024-06-21 02:13 UTC, rajivharlalka commented on backend/main.go
> +	}
It would be clearer to have a function that fetches the env variable and checks there itself whether it is empty or not. So many lines for checking feels quite repetitive and hurts readability.

2024-06-24 11:10 UTC, proffapt commented
@Bikram-ghuku what's the followup on the comments by Rajiv?

2024-06-26 09:53 UTC, harshkhandeparkar commented
> Should I update this to go 1.22 ?

Yes, please.

2024-06-26 13:03 UTC, rajivharlalka commented
Please try to wrap this PR as soon as possible.


On Wed, 26 Jun 2024 at 3:23 PM, Harsh Khandeparkar ***@***.***>
wrote:

> Should I update this to go 1.22 ?
>
> Yes, please.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/metakgp/iqps-go/pull/72#issuecomment-2191284534>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQMMFHYVFNCI4JTDHFXS4Q3ZJKFRDAVCNFSM6AAAAABJITVPY6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJRGI4DINJTGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-27 08:12 UTC, proffapt commented
@Bikram-ghuku once done, request for review from rajiv and harsh.

2024-07-10 07:05 UTC, rajivharlalka commented
status here? @Bikram-ghuku Try to finish this by eow.

2024-07-21 10:12 UTC, rajivharlalka approved these changes

2024-07-21 10:13 UTC, merged